
export const messages = {
    mikvahDetailsError: "Error fetching mikvah details:",
    govadenAnswerTooltip: "govaden-answer-tooltip",
    mikvahDetailBox: "mikvah-detail-box",
    mikvahDetailInfo: "mikvah-detail-info",
    mikvahDetailInfoLogo: "mikvah-detail-info-logo",
    mikvahDetailInfoContent: "mikvah-detail-info-content",
    collapsibleTable: "collapsible table",
    notAvailable: "NA",
    cursorPointer: "pointer",
    enterprisePaginationClass: "enterprise-pagination",
    primaryColor: "primary",
    eventFormSubmitButtonLoader: "event-form-submit-button-loader",
    fetchError: 'Error fetching data:',
    mikvahDetailWrapper: "Mikvah-Detail-Wrapper",
    errorFetchingLocation: "Please enable location access to get directions.",
    statusOk: 'OK',
    errorFetchingDirections: "The route is not available from your current location to the specified destination.",
    buttonContainedVarient: "contained",
    colorBlue: "blue",
    travelMode: "DRIVING",
    mapInputBox: "Map-input-box",
    enterOrigin: "Enter origin",
    enterDestination: "Enter destination",
    text: "text",
    showGoogleMapClass: "ShowGoogleMapClass",
    closeButtonCls: "close-button",
    marginBottom10: "marginBottom-10",
    listLocationMsg: "Below is the list of locations.",
    adminDashboardSidebarIcon: "admin-dashboard-sidebar-icon",
    assignmentIcon: "assignmentIcon",
    createAdminIcon: "createAdminIcon",
    bubbleChatUser: "bubbleChatUser",
    ruleIcon: "ruleIcon",
    categoryIcon: "categoryIcon",
    addIcon: "addIcon",
    accountBalanceIcon: "accountBalanceIcon",
    upload: "upload",
    eventIcon: "eventIcon",
    addLocationAltIcon: "addLocationAltIcon",
    liveHelpIcon: "liveHelpIcon",
    adminChat: "Admin Chat",
    geolocationText: "geolocation",
    grantedText: "granted",
    promptText: "prompt",
    errorCheckLocationPermission: "Error checking location permissions:",
    fetchErrorMessage: 'Failed to fetch the shared chat content',
    errorMessagePrefix: 'Error: ',
    noChatHistoryMessage: 'No chat history available',
    getStartedButtonText: 'Get Started with Yanki',
    sharedChatTitle: 'Yanki Shared Chat',
    sharedChatLinkTitle: 'Share Chat Link',
    shareLinkIconAlt: 'Share Chatlink',
    shareLinkPlaceholder: 'https://example.com/chat/dummy-id',
    generateLinkError: 'Failed to generate share chat ID',
    outlined: "outlined",
    normal: "normal",
    messengerAppIdPlaceholder: '<YOUR_APP_ID>',
    shareChatTitle: "Share Chat",
    clickSendMessageToEnterprise: "Click here to send message to Enterprise",
    mikvahDetailsNotFound: 'Mikvah details not found',
    shareRoute: '/share/',
    imgSize150: "150px",
    imgSize44: "44px",
    imgSize210: "210px",
    imgSize70: "70px",
    imgSize200: "200px",
    imgSize60: "60px",
    imgSize250: "250px",
    imgSize80: "80px",
    textPlain: 'text/plain',
    lastActiveTime: "lastActiveTime",
    mouseMove: "mousemove",
    keydown: "keydown",
    touchstart: "touchstart",
    success: "success",
    error: "error",
    i18nextLng: "i18nextLng",
    isLargeScreen: "(min-width: 600px)",
    taskLeftZero: "Your current limit of tasks has been reached. To continue enjoying Yanki's services, please upgrade your subscription or wait for your limit to reset. Thank you for using Yanki.",
    audioText: "audio",
    videoText: "video",
    loginYourAccountTitle: "Login your account",
    activeTab: "activeTab",
    generatedChatLink: "generatedChatLink",
    locationAllowed: "Location allowed",
    enterpriseEventMsg: "This feature is not available for Enterprise accounts. For any queries, please use the prompt ‘Ask for help’.",
};

export const classNames = {
    sharedChatContainer: "shared-chat-container",
    sharedChatPaper: "shared-chat-paper",
    sharedChatHeader: "shared-chat-header",
    sharedChatTitle: "shared-chat-title",
    sharedChatLoader: "shared-chat-loader",
    sharedChatFooter: "shared-chat-footer",
    shareChatLinkModel: "share-link-modal-title",
    shareLinkModal: "share-link-modal",
    backgroundPaper: "background.paper",
    sharedChatLinkIcons: "shared-chat-link-icons",
    sharedChatLinkInputBox: "Sharelink-input-box",
    sharedChatInput: "Sharelink-input",
    sharedChatButton: "Sharelink-input-btn",
    shareChatLinkIcon: "shareChatLinkIcon",
    tooltipPlacement: "bottom",
    altShareChatlink: "Share Chatlink",
    muiContainerUserMenu: "Mui-Container-UserMenu",
    sharedChatMsgTitle: "sharedChatMsgTitle",
    sharedChatMsgTxt: "sharedChatMsgTxt",
    xLWidth: "xl",
    languageInitialQuestions1: "initialQuestions1",
    languageInitialQuestions2: "initialQuestions2",
    languageInitialQuestions3: "initialQuestions3",
    languageInitialQuestions4: "initialQuestions4",
    shareLinkInputButton: ".Sharelink-input-btn",
    yaNewAssistantChat: "ya-new-assistant-chat",
    yaNewAssistantEmptyChat: "ya-new-assistant-empty-chat",
    yaNewChatBoxFilled: "ya-new-chat-box-filled",
    yaNewChatBox: "ya-new-chat-box",
    yaNewChatBoxEmpty: 'ya-new-chat-box-empty',
    chatSessionListSmallScreen: "ya-chat-session-list-small-screen",
    chatSessionList: "ya-chat-session-list",
    languageSwitcherButton: "language-switcher-button",
    activeLanguage: "active-language",
    homePageLanguageBtn: "Home-Page-Language-Btn",
    changeLanguageBox: "change-language-box",
    profileLogo: "profile-logo",
    profileYankiLogo: "profile-yanki-logo",
    minusMargin: "minus-margin",
    marginBottom34: "marginBottom-34",
    bold: "bold",
    marginBottom20: "marginBottom-20",
    textCenter: "text-center",
    cursorPointer: "cursor-pointer",
    colorWhite: "color-white",
    submit: "submit",
    language: "language",
    loaderContainer: "loader-container",
    flexCenter: "flex justify-center items-center min-h-70-screen",
    pdfLoaderContainer: "pdf-loader-container",
    pdfButtonStyle: "pdf-button-style",
    copyLinkLoader: "copy-link-loader",
    chatSessionListEmptyScreen: "ya-chat-session-list-empty-screen",
    noDataFoundClass: "no-data-found",
    fixedSearchBox: "fixed-search-Box",
    hiddenFixedBox: "hidden",
    confirmDialogTitle: "confirm-dialog-title",
    confirmDialogLightHeading: "confirm-dialog-light-heading",
    confirmDialogText: "confirm-dialog-text confirm-dialog-text-heading",
    confirmDeleteLightButton: "confirm-delete-light-button",
    confirmDeleteButton: "confirm-delete-button",
    deleteAccountDialogContainer: "Delete-account-MuiDialog-container",
    accountDeleteConfirmDialog: "confirm-dialog account-delete-confirm-dialog",
    confirmDialogContent: "confirm-dialog-content",
    confirmDialogTextOne: "confirm-dialog-text",
    confirmDialogActions: "confirm-dialog-actions",
    confirmCancelButton: "confirm-cancel-button",
    loadingSpinner: "loading-spinner",
    whiteColor: "white-color",
    yaNewChatBoxOneChat: "ya-new-chat-box-one-chat",
    yaNewAssistantChatNoScroll: "ya-new-assistant-chat-no-scroll", 
    enterpriseLightColor: "Enterprise-Light-Color",
};

export const apiUrls = {
    mikvahDetails: `${import.meta.env.VITE_APP_API_HOST}/api/mikvah/mikvah-details`,
    indexAndUpload: `${import.meta.env.VITE_APP_API_HOST}/api/JewishPrayerTextIndex/index-and-upload`,
    updateDocumentKeywords: (pdfId, tags) =>
        `${import.meta.env.VITE_APP_API_HOST}/api/JewishPrayerTextIndex/update-document-keywords?documentId=${encodeURIComponent(pdfId)}&newKeywords=${encodeURIComponent(JSON.stringify(tags))}`,
    documentMapping: (pageNumber) =>
        `${import.meta.env.VITE_APP_API_HOST}/api/JewishPrayerTextIndex/document-mapping?pageNumber=${pageNumber}&pageSize=10`,
    personalAssistantEmail: `${import.meta.env.VITE_APP_API_HOST}/api/yanki-ai/personal-assistant-email`,
    sharedChatApiUrl: (sharedChatId) => `${import.meta.env.VITE_APP_API_HOST}/api/yanki-ai/get-shared-chat?sharedChatId=${sharedChatId}`,
    generateShareChatIdApiUrl: (chatId) => `${import.meta.env.VITE_APP_API_HOST}/api/yanki-ai/generate-share-chat-id?chatId=${chatId}`,
    chatLinkBaseUrl: `${window.location.origin}/share/`,
    whatsappShareUrl: 'https://api.whatsapp.com/send?text=',
    twitterShareUrl: 'https://twitter.com/intent/tweet?url=',
    smsShareUrl: 'sms:?&body=',
    instagramShareUrl: 'https://www.instagram.com/?url=',
    messengerShareUrl: (chatLink, appId) => `https://www.facebook.com/dialog/send?link=${encodeURIComponent(chatLink)}&app_id=${appId}`,
    getUserLanguage: `${import.meta.env.VITE_APP_API_HOST}/api/language-selection/get-user-language`,
    updateUserLanguage: `${import.meta.env.VITE_APP_API_HOST}/api/language-selection/update-user-language`,
    getEventsPublicationAreas: `${import.meta.env.VITE_APP_API_HOST}/api/event-publication-area/get-events-publicationAreas`,
    getEventsLocations: `${import.meta.env.VITE_APP_API_HOST}/api/event-location/get-events-locations`,
    getEventsTypes: `${import.meta.env.VITE_APP_API_HOST}/api/event-type/get-events-types`,
    addEventUrl: `${import.meta.env.VITE_APP_API_HOST}/api/events/add-event`,
    imageUploadUrl: (eventId) => `${import.meta.env.VITE_APP_API_HOST}/api/events/event-image-upload?eventId=${eventId}`,
    getUserSubscriptionById: (userId) => `${import.meta.env.VITE_APP_API_HOST}/api/event-subscription/get-user-subscriptionById?userId=${userId}`,
    addSubscriptionUrl: `${import.meta.env.VITE_APP_API_HOST}/api/event-subscription/add-subscription`,
    updateEventSubscription: (subscriptionId) => `${import.meta.env.VITE_APP_API_HOST}/api/event-subscription/update-event-subscription?subscriptionId=${subscriptionId}`,
    deleteSubscription: (subscriptionId) => `${import.meta.env.VITE_APP_API_HOST}/api/event-subscription/delete-subscription?subscriptionId=${subscriptionId}`,
    updateUserLanguage: `${import.meta.env.VITE_APP_API_HOST}/api/language-selection/update-user-language`,
    getUpcomingReminders: (userId) => `${import.meta.env.VITE_APP_API_HOST}/api/reminder/get-upcoming-reminder-userId?userId=${userId}`,
    safetyCheckerEmail: `${import.meta.env.VITE_APP_API_HOST}/api/yanki-ai/safety-checker-email`,
    sendMailToEnterprise: `${import.meta.env.VITE_APP_API_HOST}/api/yanki-ai/send-mail-to-enterprise`,
    sendMailToRabbi: `${import.meta.env.VITE_APP_API_HOST}/api/yanki-ai/send-mail-to-rabbi`,
    getCustomPrompt: `${import.meta.env.VITE_APP_API_HOST}/api/CustomPrompt/get-custom-prompt`,
    addCustomPrompt: `${import.meta.env.VITE_APP_API_HOST}/api/CustomPrompt/add-custom-prompt`,
    deleteCustomPrompt: `${import.meta.env.VITE_APP_API_HOST}/api/CustomPrompt/delete-custom-prompt`,
    updateCustomPrompt: `${import.meta.env.VITE_APP_API_HOST}/api/CustomPrompt/update-custom-prompt`,
    verifyEmail: `${import.meta.env.VITE_APP_API_HOST}/api/auth/verify-email`,
    changePassword: `${import.meta.env.VITE_APP_API_HOST}/api/auth/change-password`,
    currentPhoneNumber: `${import.meta.env.VITE_APP_API_HOST}/api/auth/current-phoneNumber`,
    getEnterprisesCategories: `${import.meta.env.VITE_APP_API_HOST}/api/yanki-ai/get-enterprises-categories`,
    registerUser: `${import.meta.env.VITE_APP_API_HOST}/api/auth/register`,
    forgotPassword: (email, userType) => `${import.meta.env.VITE_APP_API_HOST}/api/auth/forgot-password?email=${email}&userType=${userType}`,
    login: `${import.meta.env.VITE_APP_API_HOST}/api/auth/login`,
    verifyGoogleAccessToken: `${import.meta.env.VITE_APP_API_HOST}/api/auth/verify-google-access-token`,
    resetPassword: `${import.meta.env.VITE_APP_API_HOST}/api/auth/reset-password`,
    registerUser: `${import.meta.env.VITE_APP_API_HOST}/api/auth/register`,
    changePhoneNumber: `${import.meta.env.VITE_APP_API_HOST}/api/auth/change-phoneNumber`,
    getAllEvents: (pageNumber) =>
        `${import.meta.env.VITE_APP_API_HOST}/api/events/get-allevents?pageNumber=${pageNumber}`,
    deleteDocument: `${import.meta.env.VITE_APP_API_HOST}/api/JewishPrayerTextIndex/delete-document`,
};

export const membershipApiUrls = {
    getRemainingMessageTask: `${import.meta.env.VITE_APP_API_HOST}/api/stripe/get-remaining-message-task`,
    getAllProducts: `${import.meta.env.VITE_APP_API_HOST}/api/stripe/get-all-products`,
    createCustomer: (userId) => `${import.meta.env.VITE_APP_API_HOST}/api/stripe/create-customer?userId=${userId}`,
    subscribeProductPlan: `${import.meta.env.VITE_APP_API_HOST}/api/stripe/subscribe-product-plan`,
    getCustomerId: `${import.meta.env.VITE_APP_API_HOST}/api/stripe/get-customer-id`,
    createCustomerPortal: (queryString) => `${import.meta.env.VITE_APP_API_HOST}/api/stripe/create-customer-portal?customerId=${queryString}`,
    upgradeSubscription: (priceId) => `${import.meta.env.VITE_APP_API_HOST}/api/stripe/upgrade-subscription?newPriceId=${priceId}`,
    downgradeSubscription: (priceId) => `${import.meta.env.VITE_APP_API_HOST}/api/stripe/downgrade-subscription?newPriceId=${priceId}`,
    paymentForAdditionalTask: `${import.meta.env.VITE_APP_API_HOST}/api/stripe/payment-for-additional-task`,
    allAnswers: (chatId) => `${import.meta.env.VITE_APP_API_HOST}/api/yanki-ai/all-answers?chatId=${chatId}`,
    chatSessionList: (pageNumber) => `${import.meta.env.VITE_APP_API_HOST}/api/yanki-ai/chat-session-list?pageNumber=${pageNumber}&pageSize=30`,
    chatHistory: (chatId, pageNumber, pageSize) => `${import.meta.env.VITE_APP_API_HOST}/api/yanki-ai/chat-history?chatId=${chatId}&pageNumber=${pageNumber}&pageSize=${pageSize}`,
    chatHistoryData: (chatId, pageSize) => `${import.meta.env.VITE_APP_API_HOST}/api/yanki-ai/chat-history?chatId=${chatId}&pageNumber=1&pageSize=${pageSize}`,
    chatHistoryFetch: (chatId, pageSize = 20) => `${import.meta.env.VITE_APP_API_HOST}/api/yanki-ai/chat-history?chatId=${chatId}&pageNumber=1&pageSize=${pageSize}`,
    deleteChatSession: (chatId) => `${import.meta.env.VITE_APP_API_HOST}/api/yanki-ai/delete-chat-session?chatId=${chatId}`,
    getUserLanguage: `${import.meta.env.VITE_APP_API_HOST}/api/language-selection/get-user-language`,
}

export const mapContainerStyle = {
    width: '100%',
    height: '400px',
};

export const sourceSelectionStrings = {
    small: "small",
    defaultOption: "YankiAIChoice",
    anchorOriginHorizontal: "right",
    anchorOriginVertical: "bottom",
    transformOriginHorizontal: "right",
    transformOriginVertical: "top",
    menuClassName: "source-selection-menu",
    selectedClass: "selected",
    disabledClass: "disabled",
    menuItemClass: "menu-item",
    localStorageKey: 'selectedOption',
    defaultOption2: "PersonalAssistant",
    sourceSelectioniconBox: "source-selectionicon",
    sourceSelectionTitle: "Source Selection",
    accountMenu: "account-menu",
    true: "true",
    auto: "auto",
    menuItemButton: "menu-item-button",
    text: "text",
    yaMainTextBbox: "ya-main-text-box",
    yaMainTextHeading90px: "90px",
    yaMainTextHeading70px: "70px",
    logo: "logo",
    homeTableScroll: "home-table-scroll",
    yaMobilePrompt: "ya-mobile-prompt",
    yaHomeTableBtn: "ya-home-table-btn",
    yaSearchDarkTheme: "ya-search-dark-theme",
    yaSearchLightTheme: "ya-search-light-theme",
    carouselItem: "carousel-item",
    newHomeInitialQuestions: "new-home-initial-questions",
    transformAnimation: "transform 500ms ease 0s",
    yaSliderBtn: "ya-slider-btn",
    yaMainTextHeading: "ya-main-text-heading",
    yankeeDirectory: "YankiDirectory",
    yankeeLibrary: "YankiLibrary",
    myZmanim: "MyZmanim",
    goDaven: "Godaven",
    torahAnytime: "Torahanytime",
    isItKosher: "IsItKosher",
    mikvah: "Mikvah",
    personalAssistant: "PersonalAssistant",
    logoSrc: "/auth-logo-dark.svg", 
    logoWidth: "160px", 
    logoHeight: "50px", 
    logoClassName: "ya-logo-img",
    myZamninLogoWidth: "110px",
    yankiLogoWidth: "180px",
    yankiLogoHeight: "140px",
    isItKosherLogoHeight: "65px",
    godavenLogoHeight: "50px",
    homeMinusMargin: "home-minus-margin",
    marginBottom20: "margin-bottom-20",
}
export const headers = {
    "Content-Type": "multipart/form-data",
};
