
export const messages = {
    mikvahDetailsError: "Error fetching mikvah details:",
    govadenAnswerTooltip: "govaden-answer-tooltip",
    mikvahDetailBox: "mikvah-detail-box",
    mikvahDetailInfo: "mikvah-detail-info",
    mikvahDetailInfoLogo: "mikvah-detail-info-logo",
    mikvahDetailInfoContent: "mikvah-detail-info-content",
    collapsibleTable: "collapsible table",
    notAvailable: "NA",
    cursorPointer: "pointer",
    enterprisePaginationClass: "enterprise-pagination",
    primaryColor: "primary",
    eventFormSubmitButtonLoader: "event-form-submit-button-loader",
    fetchError: 'Error fetching data:',
    mikvahDetailWrapper: "Mikvah-Detail-Wrapper",
    errorFetchingLocation: "Please enable location access to get directions.",
    statusOk: 'OK',
    errorFetchingDirections: "The route is not available from your current location to the specified destination.",
    nameText: "Name",
    addressText: "Address",
    locationText: "Location",
    buttonContainedVarient: "contained",
    colorBlue: "blue",
    travelMode: "DRIVING",
    mapInputBox: "Map-input-box",
    enterOrigin: "Enter origin",
    enterDestination: "Enter destination",
    text: "text",
    showGoogleMapClass: "ShowGoogleMapClass",
    closeButtonCls: "close-button",
    marginBottom10: "marginBottom-10",
    listLocationMsg: "Below is the list of locations.",
    adminDashboardSidebarIcon: "admin-dashboard-sidebar-icon",
    assignmentIcon: "assignmentIcon",
    createAdminIcon: "createAdminIcon",
    bubbleChatUser: "bubbleChatUser",
    ruleIcon: "ruleIcon",
    categoryIcon: "categoryIcon",
    addIcon: "addIcon",
    accountBalanceIcon: "accountBalanceIcon",
    upload: "upload",
    eventIcon: "eventIcon",
    addLocationAltIcon: "addLocationAltIcon",
    liveHelpIcon: "liveHelpIcon",
    adminChat: "Admin Chat",
    geolocationText : "geolocation",
    grantedText : "granted",
    errorCheckLocationPermission : "Error checking location permissions:",
};

export const apiUrls = {
    mikvahDetails: `${import.meta.env.VITE_APP_API_HOST}/api/mikvah/mikvah-details`,
    indexAndUpload: `${import.meta.env.VITE_APP_API_HOST}/api/JewishPrayerTextIndex/index-and-upload`,
    updateDocumentKeywords: (pdfId, tags) =>
        `${import.meta.env.VITE_APP_API_HOST}/api/JewishPrayerTextIndex/update-document-keywords?documentId=${encodeURIComponent(pdfId)}&newKeywords=${encodeURIComponent(JSON.stringify(tags))}`,
    documentMapping: (pageNumber) =>
        `${import.meta.env.VITE_APP_API_HOST}/api/JewishPrayerTextIndex/document-mapping?pageNumber=${pageNumber}&pageSize=10`,
    personalAssistantEmail:`${import.meta.env.VITE_APP_API_HOST}/api/yanki-ai/personal-assistant-email`,
};

export const mapContainerStyle = {
    width: '100%',
    height: '400px',
};